### PR TITLE
Update index.md to include recent reproducibility examples

### PR DESCRIPTION
**Pull request by LucyMcGowan**

### CODE REVIEW

**Comment by paciorek** [comment]
@LucyMcGowan The first two new examples don't have ACC forms (presumably as they are T&M papers from before the requirement applied to T&M).  I think that we want all examplars to have ACC forms. Sorry, this should probably have occurred to me as we were discussing this last week.

**Comment by LucyMcGowan** [comment]
Oh no problem! I'll pick two others

**Comment by paciorek** [comment]
I noticed that the ACC form for the Schultheiss article has the code link be to the expired anonymous repository (the link to an actual GH repository is in the paper though).

Do we think that is a problem? I may well be misunderstanding/missing something here, but given you and I had started a discussion about concerns about use of anonymous repositories, it feels to me that pointing authors to a repo that does this is probably not what we want. Ideally we'd have the authors update the ACC form link, but I'm not sure of a mechanism for that given the figshare link is presumably meant to freeze things as they were at time of publication. 

If we do leave that one out, three exemplars may be fine, or if you had another possibility in mind we could substitute it in.

**Comment by paciorek** [comment]
@LucyMcGowan no particular hurry, but just a ping about this.

**Comment by LucyMcGowan** [comment]
@paciorek sorry for the delay! I didn't notice that the GH link is correct in the paper -- that is good! I removed that example since it did have the expired link and I agree this would be a good thing to discuss at the next meeting (using anonymous links in the ACC forms)

**Pull request merged**
